require "nokogiri"
require "pathname"
require "fileutils"
require "pry-byebug"

RSpec.describe DSLGenerator do
  let(:lib_dir) { Pathname("lib_dir") }
  let(:gem_dir) { lib_dir.join("gem_dir") }
  let(:dsl_dir) { gem_dir.join("dsl") }
  let(:specifications_dir) { lib_dir.join("specifications") }
  let(:idl_xml_path) { specifications_dir.join("idl.xml") }
  let(:xml_content) { '<jmeterTestPlan><hashTree><someElement testclass="SomeTest" testname="some test"/></hashTree></jmeterTestPlan>' }
  let(:xml_element) { Nokogiri::XML(xml_content).at_xpath("//someElement") }
  let(:mock_dsl_file_path) { dsl_dir.join("some_test.rb") }
  let(:dsl_md_file_path) { "#{lib_dir}/../DSL.md" }
  let(:rbs_file_path) { "sig/jmeter_perf.rbs" }
  let(:rbs_content) do
    <<~RBS
      class JmeterPerf
        ## AUTOGENERATED - DSL methods RBS
        old content
        ## AUTOGENERATED - DSL methods RBS
      end
    RBS
  end

  before do
    allow(File).to receive(:open).with(idl_xml_path).and_return(StringIO.new(xml_content))
    allow(File).to receive(:write)
    allow(File).to receive(:read).with(rbs_file_path).and_return(rbs_content)
    allow(Dir).to receive(:mkdir_p).with(dsl_dir, 0o700)
    allow(Dir).to receive(:exist?).with(dsl_dir).and_return(false)

    allow(Nokogiri::XML::Document).to receive(:parse).and_return(Nokogiri::XML(xml_content))
  end

  describe "#generate" do
    subject(:dsl_generator) { described_class.new(lib_dir:, gem_dir:, dsl_dir:, idl_xml_path:) }

    it "parses the idl.xml file" do
      expect { dsl_generator.generate }.not_to raise_error
    end

    it "creates the DSL directory if it does not exist" do
      expect(FileUtils).to receive(:mkdir_p).with(dsl_dir)
      dsl_generator.generate
    end

    it "generates a DSL method file for each test element in the XML" do
      expected_dsl_content = <<~RUBY
        module JmeterPerf
          class DSL
            def some_test(params = {}, &)
              node = JmeterPerf::SomeTest.new(params)
              attach_node(node, &)
            end
          end

          class SomeTest
            attr_accessor :doc
            include Helper

            def initialize(params = {})
              testname = params.is_a?(Array) ? "SomeTest" : (params[:name] || "SomeTest")
              @doc = Nokogiri::XML(<<~EOS.strip_heredoc)
        #{xml_element.to_xml.gsub(/testname=".+?"/, 'testname="#{testname}"').gsub(/^/, "        ")}
              EOS
              update params
              update_at_xpath params if params.is_a?(Hash) && params[:update_at_xpath]
            end
          end
        end
      RUBY

      expect(File).to receive(:write).with("#{dsl_dir}/some_test.rb", expected_dsl_content)
      dsl_generator.generate
    end

    it "writes the DSL methods documentation to DSL.md" do
      expected_md_content = <<~MARKDOWN
        # JmeterPerf::DSL methods
        - SomeTest
          `some_test`
      MARKDOWN
        .chomp

      expect(File).to receive(:write).with(dsl_md_file_path, expected_md_content)
      dsl_generator.generate
    end

    it "updates the RBS file with the generated DSL methods" do
      expected_rbs_content = <<~RBS
        class JmeterPerf
            ## AUTOGENERATED - DSL methods RBS

            def some_test: (Hash[Symbol, untyped], &block) -> void

            ## AUTOGENERATED - DSL methods RBS
        end
      RBS

      expect(File).to receive(:write).with(rbs_file_path, expected_rbs_content)
      dsl_generator.generate
    end
  end
end
