name: CI
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-ci
  cancel-in-progress: true
jobs:
  lint:
    permissions:
      checks: write
      contents: write
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
