name: CodeGuard
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-codeguard
  cancel-in-progress: true
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
