name: Lint
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-lint
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.{rb,ru,rake,gemspec}
            Gemfile
            jmeter_perf.gemspec
          files_ignore: |
            .bundle/**/*
            .git/**/*
            sorbet/**/*
            Gemfile.lock
            tmp/**/*
            vendor/**/*
          separator: " "
      - name: Set up Ruby
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ruby/setup-ruby@v1.197.0
        env:
          BUNDLE_ONLY: ci
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Lint Code
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: wearerequired/lint-action@v2.3.0
        env:
          BUNDLE_ONLY: ci
        with:
          auto_fix: true
          rubocop: true
          rubocop_command_prefix: bundle exec
          rubocop_args: --parallel ${{ steps.changed-files.outputs.all_changed_files }}