name: Release
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-release
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  lint:
    permissions:
      checks: write
      contents: write
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: ci
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.197.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: "lib/jmeter_perf/version.rb"
      - name: Bump Patch Version
        id: semver
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          bundle exec bump patch --no-commit
          echo "semver=$(bundle exec bump current)" >> $GITHUB_OUTPUT
      - name: Commit Version Bump
        if: steps.changed-files.outputs.any_changed == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          add: "lib/jmeter_perf/version.rb"
          default_author: github_actions
          message: "Bump version to ${{ steps.semver.outputs.semver }}"
          tag: "v${{ steps.semver.outputs.semver }}"
  release:
    name: Release gem to RubyGems.org
    needs: [version]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.197.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - uses: rubygems/release-gem@v1
